model:
  name: "elmo"
  hub_url: "https://tfhub.dev/google/elmo/3"
  embedding_dim: 1024

clustering:
  algorithm: "kmeans" 
  n_clusters: 10

visualization:
  method: "tsne"
  perplexity: 30
  n_iter: 1000
  random_state: 42

evaluation:
  metrics: ["silhouette", "davies_bouldin", "calinski_harabasz"]
  search_metrics: ["precision_k", "mrr", "ndcg"]

data:
  max_samples: 10000
  subset_for_demo: true